language: python
python:
    - "2.7"

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/arduino
    - PLATFORMIO_CI_SRC=examples/mbed

install:
    - pip install -U platformio

script:
    - platformio ci --project-conf=examples/arduino/platformio.ini --lib="."
